"""Names of cities in many languages adapted with changes and omissions from
https://en.wikipedia.org/wiki/List_of_names_of_European_cities_in_different_languages
with the addition of common abbreviations."""

munich_in_many_languages = [
    "Minca",
    "Minga",
    "Minhen",
    "Minhene",
    "Minkhn",
    "Miunchenas",
    "Miyūnikh",
    "Myunkhen",
    "Mnichov",
    "Mníchov",
    "Monachium",
    "Mnichów",
    "Monaco",
    "Mónakho",
    "Μόναχο",
    "Monakovo",
    "München",
    "Munĥeno",
    "Munkeno",
    "Múnic",
    "Munic",
    "Múnich",
    "Münih",
    "Mùníhēi",
    "Munique",
    "Mûnik",
    "Munikh",
    "Muunsjen",
    "Myunhen",
    "Mwinhen",
    "مونیخ",
    "Mynih",
]

stuttgart_in_many_languages = [
    "Schduagert",
    "Estugarda",
    "Shututtogaruto",
    "Štíhrad",
    "Stoccarda",
    "Stoutgárdhi",
    "Στουτγάρδη",
    "Štutgartas",
    "Štutgarte",
    "Stuttgart",
    "Syututeugareuteu",
    "슈투트가르트",
    "Stutty",
    "Stuggi",
]

berlin_in_many_languages = [
    "Barlīn",
    "Barliń",
    "Barlin",
    "Beirlín",
    "Bereullin",
    "Perŭllin",
    "Berlien",
    "Berliin",
    "Berliini",
    "Berlijn",
    "Berlim",
    "Berlin",
    "ברלין",
    "Berlin",
    "בערלין",
    "Berlīne",
    "Berlino",
    "Berlyn",
    "Berlynas",
    "Berurin",
    "ベルリン",
    "Bólín",
    "Verolíno",
    "Βερολίνο",
]
